import express from "express";
import bodyParser from "body-parser";
import mongoose from "mongoose";
import cors from "cors";
import dotenv from "dotenv";
import cookieParser from "cookie-parser"; // For parsing cookies
import csrfProtection from "./middleware/csrfMiddleware.js"

import adminRoutes from "./routes/adminRoutes.js";
import studentRoutes from "./routes/studentRoutes.js";
import facultyRoutes from "./routes/facultyRoutes.js";
import { addDummyAdmin } from "./controller/adminController.js";
const app = express();
dotenv.config();

app.use(bodyParser.json({ limit: "30mb", extended: true }));
app.use(bodyParser.urlencoded({ limit: "30mb", extended: true }));

// CORS configuration for allowing localhost:3000 and its subdomains
const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests from localhost:3000 or any of its subdomains
    if (!origin || origin === 'http://localhost:3000' || origin.endsWith('.localhost:3000')) {
      callback(null, true);
    } else {
      // Reject the request
      callback(new Error('Not allowed by CORS')); 
    }
  },
  // Specify allowed methods
  methods: ['GET', 'POST', 'PUT', 'DELETE'], 
  // Specify allowed headers
  allowedHeaders: ['Content-Type', 'Authorization', 'X-CSRF-Token'], // Added X-CSRF-Token
  // Allow cookies and credentials to be sent
  credentials: true, 
};

// Apply the CORS middleware with the options
app.use(cors(corsOptions));

// Handling CORS errors globally
app.use((err, req, res, next) => {
  if (err instanceof Error && err.message === 'Not allowed by CORS') {
    res.status(403).json({ message: 'CORS policy does not allow access from this origin.' });
  } else {
    next(err); // Pass on any other errors
  }
});

// Middleware to parse cookies (necessary for CSRF protection)
app.use(cookieParser());
app.use(csrfProtection);

// Middleware to log the CSRF token for debugging
app.use((req, res, next) => {
  console.log('Headers:', req.headers); // Log all incoming headers
  console.log("CSRF Token:", req.csrfToken()); // Log the CSRF token to the console
  console.log('Incoming request:', req.method, req.path);
  console.log('CSRF Token:', req.headers['x-csrf-token']); 
  next();
});

// Serve the CSRF token to the frontend at a specific endpoint
app.get("/api/csrf-token", (req, res) => {
  const csrfToken = req.csrfToken(); // This will be generated by csurf middleware
  console.log("Generated CSRF Token:", csrfToken);
  res.json({ csrfToken: req.csrfToken() });
});

// Error handling for CSRF token validation
app.use((err, req, res, next) => {
  if (err.code === 'EBADCSRFTOKEN') {
    return res.status(403).json({ message: 'Invalid CSRF token' });
  }
  next(err);
});

app.use("/api/admin", adminRoutes);
app.use("/api/faculty", facultyRoutes);
app.use("/api/student", studentRoutes);

// Root route
app.get("/", (req, res) => {
  res.send("Hello to college erp API");
});

const PORT = process.env.PORT || 5001;
mongoose
  .connect(process.env.CONNECTION_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    addDummyAdmin(); // Adds a dummy admin on server start
    app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
  })
  .catch((error) => console.log("Mongo Error", error.message));
